// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9BumTZi2sEXesNrnOHFiJ2dQzW0Hpes',
    appId: '1:331059270060:web:ed36e163c1fd0e4e12ea09',
    messagingSenderId: '331059270060',
    projectId: 'siraj-e4a11',
    authDomain: 'siraj-e4a11.firebaseapp.com',
    storageBucket: 'siraj-e4a11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcB9lfr5kkG2OsJzsDm2hZtt-eppSUUmA',
    appId: '1:331059270060:android:1ec40268ba58348c12ea09',
    messagingSenderId: '331059270060',
    projectId: 'siraj-e4a11',
    storageBucket: 'siraj-e4a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0OcijMZQRvG_al3fUncTVu_kkF0XNg4s',
    appId: '1:331059270060:ios:1ce7ce5146324a5012ea09',
    messagingSenderId: '331059270060',
    projectId: 'siraj-e4a11',
    storageBucket: 'siraj-e4a11.firebasestorage.app',
    iosClientId: '331059270060-g9bb92gha3rrg8kktqaqhvkk2q83p1gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.siraj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0OcijMZQRvG_al3fUncTVu_kkF0XNg4s',
    appId: '1:331059270060:ios:1ce7ce5146324a5012ea09',
    messagingSenderId: '331059270060',
    projectId: 'siraj-e4a11',
    storageBucket: 'siraj-e4a11.firebasestorage.app',
    iosClientId: '331059270060-g9bb92gha3rrg8kktqaqhvkk2q83p1gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.siraj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs9BumTZi2sEXesNrnOHFiJ2dQzW0Hpes',
    appId: '1:331059270060:web:4fcdd497313fde2912ea09',
    messagingSenderId: '331059270060',
    projectId: 'siraj-e4a11',
    authDomain: 'siraj-e4a11.firebaseapp.com',
    storageBucket: 'siraj-e4a11.firebasestorage.app',
  );
}
